-- Migration 017: Invoice & Printer Settings table for persistent, branch-aware configuration
CREATE TABLE IF NOT EXISTS invoice_printer_settings (
    branch_id TEXT PRIMARY KEY REFERENCES branches(id) ON DELETE CASCADE,
    shop_name TEXT NOT NULL DEFAULT 'Niazi Mobile Mart',
    branch_name TEXT NOT NULL DEFAULT 'Main Branch',
    address TEXT NOT NULL DEFAULT '',
    phone TEXT NOT NULL DEFAULT '',
    secondary_phone TEXT DEFAULT '',
    whatsapp TEXT DEFAULT '',
    email TEXT DEFAULT '',
    logo_url TEXT DEFAULT '',
    tax_number TEXT DEFAULT '',
    printer_type TEXT NOT NULL DEFAULT 'THERMAL_80MM',
    connection_type TEXT NOT NULL DEFAULT 'BROWSER_PRINT',
    paper_width TEXT NOT NULL DEFAULT '80mm',
    font_family TEXT NOT NULL DEFAULT 'sans-serif',
    font_size INT NOT NULL DEFAULT 12,
    margin_top INT NOT NULL DEFAULT 0,
    margin_bottom INT NOT NULL DEFAULT 0,
    margin_left INT NOT NULL DEFAULT 0,
    margin_right INT NOT NULL DEFAULT 0,
    show_logo INT NOT NULL DEFAULT 1,
    show_shop_info INT NOT NULL DEFAULT 1,
    show_barcode INT NOT NULL DEFAULT 1,
    show_qr INT NOT NULL DEFAULT 0,
    show_tax INT NOT NULL DEFAULT 0,
    show_discount INT NOT NULL DEFAULT 1,
    auto_print INT NOT NULL DEFAULT 0,
    print_copy_count INT NOT NULL DEFAULT 1,
    return_policy TEXT DEFAULT 'Goods once sold can only be returned/exchanged within 3 days with original receipt.',
    warranty_instructions TEXT DEFAULT 'Warranty claims require original invoice. Physical or liquid damage voids warranty.',
    footer_text TEXT DEFAULT 'Thank you for shopping with us!',
    updated_at TEXT NOT NULL
);
