module.exports = {
  MARKETPLACE_ENABLED: false,
  PUBLIC_SEARCH_ENABLED: false,
  PUBLIC_PRODUCT_INDEXING: false,
  PUBLIC_SHOP_DIRECTORY: false,
  PUBLIC_PRODUCT_PAGE: false,
  PUBLIC_PRODUCT_API: false,
  PUBLIC_SEARCH_API: false,
  PUBLIC_AVAILABILITY: false,
  PUBLIC_REVIEWS: false,
  PUBLIC_FEATURED_PRODUCTS: false,
};
